# Deprecated in Spring Boot 3.5 metadata, replaced by server.max-http-request-header-size
server.max-http-header-size=16KB

# Deprecated in Spring Boot 3.5 metadata, replaced by server.forward-headers-strategy
server.use-forward-headers=true

# Deprecated in Spring Boot 3.5 metadata, replaced by spring.http.codec.max-in-memory-size
spring.codec.max-in-memory-size=1MB
